### ISSUE TITLE
latest release completely broken :(

### ISSUE THREAD

**Issue by GeoffWilliams** [declarativesystems/pe_kit#3]
```
INFO:kivy:[CutBuffer   ] cut buffer support enabled
INFO:__main__:starting docker_init in own thread
DEBUG:docker.auth.auth:Trying paths: ['/home/geoff/.docker/config.json', '/home/geoff/.dockercfg']
INFO:__main__:starting update_status in own thread
DEBUG:docker.auth.auth:Found file at path: /home/geoff/.docker/config.json
DEBUG:docker.auth.auth:Found 'auths' section
DEBUG:docker.auth.auth:Found entry (registry=u'https://index.docker.io/v1/', username=u'geoffwilliams')
INFO:__main__:Docker URL: https://localhost
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: Retry(total=0, connect=None, read=False, redirect=None, status=None) -> Retry(total=Retry(total=0, connect=None, read=False, redirect=None, status=None), connect=None, read=None, redirect=0)
WARNING:requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: localhost
 Exception in thread Thread-1:
WARNING:kivy:stderr: Exception in thread Thread-1:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "./main.py", line 785, in docker_init
WARNING:kivy:stderr:   File "./main.py", line 785, in docker_init
     self.cleanup_container(self.container["agent"])
WARNING:kivy:stderr:     self.cleanup_container(self.container["agent"])
   File "./main.py", line 755, in cleanup_container
WARNING:kivy:stderr:   File "./main.py", line 755, in cleanup_container
     if self.cli.inspect_container(container["name"]):
WARNING:kivy:stderr:     if self.cli.inspect_container(container["name"]):
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
     return f(self, resource_id, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, resource_id, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/container.py", line 197, in inspect_container
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/container.py", line 197, in inspect_container
     self._get(self._url("/containers/{0}/json", container)), True
WARNING:kivy:stderr:     self._get(self._url("/containers/{0}/json", container)), True
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
     return f(self, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
WARNING:kivy:stderr:     return self.get(url, **self._set_request_timeout(kwargs))
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
     return self.request('GET', url, **kwargs)
WARNING:kivy:stderr:     return self.request('GET', url, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
     resp = self.send(prep, **send_kwargs)
WARNING:kivy:stderr:     resp = self.send(prep, **send_kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
     r = adapter.send(request, **kwargs)
WARNING:kivy:stderr:     r = adapter.send(request, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
WARNING:kivy:stderr:     timeout=timeout
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
     timeout_obj = self._get_timeout(timeout)
WARNING:kivy:stderr:     timeout_obj = self._get_timeout(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
     return Timeout.from_float(timeout)
WARNING:kivy:stderr:     return Timeout.from_float(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
     return Timeout(read=timeout, connect=timeout)
WARNING:kivy:stderr:     return Timeout(read=timeout, connect=timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
     self._connect = self._validate_timeout(connect, 'connect')
WARNING:kivy:stderr:     self._connect = self._validate_timeout(connect, 'connect')
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
     "int or float." % (name, value))
WARNING:kivy:stderr:     "int or float." % (name, value))
 ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
WARNING:kivy:stderr: ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
 
WARNING:kivy:stderr: 
DEBUG:__main__:clicked toggle_advanced()
DEBUG:__main__:...exiting toggle_advanced()
[INFO   ] [GL          ] NPOT texture support is available
INFO:kivy:[GL          ] NPOT texture support is available
INFO:__main__:Warning:  This tool is for test and evaulation use only
and is not supported by Puppet.  The images used are NOT
secure and must not be used for production use.
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: Retry(total=0, connect=None, read=False, redirect=None, status=None) -> Retry(total=Retry(total=0, connect=None, read=False, redirect=None, status=None), connect=None, read=None, redirect=0)
WARNING:requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: localhost
 Exception in thread Thread-2:
WARNING:kivy:stderr: Exception in thread Thread-2:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "./main.py", line 703, in update_status
WARNING:kivy:stderr:   File "./main.py", line 703, in update_status
     self.daemon_status = self.daemon_alive()
WARNING:kivy:stderr:     self.daemon_status = self.daemon_alive()
   File "./main.py", line 862, in daemon_alive
WARNING:kivy:stderr:   File "./main.py", line 862, in daemon_alive
     version_info = self.cli.version()
WARNING:kivy:stderr:     version_info = self.cli.version()
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
     return self._result(self._get(url), json=True)
WARNING:kivy:stderr:     return self._result(self._get(url), json=True)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
     return f(self, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
WARNING:kivy:stderr:     return self.get(url, **self._set_request_timeout(kwargs))
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
     return self.request('GET', url, **kwargs)
WARNING:kivy:stderr:     return self.request('GET', url, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
     resp = self.send(prep, **send_kwargs)
WARNING:kivy:stderr:     resp = self.send(prep, **send_kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
     r = adapter.send(request, **kwargs)
WARNING:kivy:stderr:     r = adapter.send(request, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
WARNING:kivy:stderr:     timeout=timeout
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
     timeout_obj = self._get_timeout(timeout)
WARNING:kivy:stderr:     timeout_obj = self._get_timeout(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
     return Timeout.from_float(timeout)
WARNING:kivy:stderr:     return Timeout.from_float(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
     return Timeout(read=timeout, connect=timeout)
WARNING:kivy:stderr:     return Timeout(read=timeout, connect=timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
     self._connect = self._validate_timeout(connect, 'connect')
WARNING:kivy:stderr:     self._connect = self._validate_timeout(connect, 'connect')
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
     "int or float." % (name, value))
WARNING:kivy:stderr:     "int or float." % (name, value))
 ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
WARNING:kivy:stderr: ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
 
WARNING:kivy:stderr: 
^CERROR:__main__:someone pressed ctrl+c - exit
INFO:kivy:[CutBuffer   ] cut buffer support enabled
INFO:__main__:starting docker_init in own thread
DEBUG:docker.auth.auth:Trying paths: ['/home/geoff/.docker/config.json', '/home/geoff/.dockercfg']
INFO:__main__:starting update_status in own thread
DEBUG:docker.auth.auth:Found file at path: /home/geoff/.docker/config.json
DEBUG:docker.auth.auth:Found 'auths' section
DEBUG:docker.auth.auth:Found entry (registry=u'https://index.docker.io/v1/', username=u'geoffwilliams')
INFO:__main__:Docker URL: https://localhost
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: Retry(total=0, connect=None, read=False, redirect=None, status=None) -> Retry(total=Retry(total=0, connect=None, read=False, redirect=None, status=None), connect=None, read=None, redirect=0)
WARNING:requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: localhost
 Exception in thread Thread-1:
WARNING:kivy:stderr: Exception in thread Thread-1:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "./main.py", line 785, in docker_init
WARNING:kivy:stderr:   File "./main.py", line 785, in docker_init
     self.cleanup_container(self.container["agent"])
WARNING:kivy:stderr:     self.cleanup_container(self.container["agent"])
   File "./main.py", line 755, in cleanup_container
WARNING:kivy:stderr:   File "./main.py", line 755, in cleanup_container
     if self.cli.inspect_container(container["name"]):
WARNING:kivy:stderr:     if self.cli.inspect_container(container["name"]):
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
     return f(self, resource_id, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, resource_id, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/container.py", line 197, in inspect_container
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/container.py", line 197, in inspect_container
     self._get(self._url("/containers/{0}/json", container)), True
WARNING:kivy:stderr:     self._get(self._url("/containers/{0}/json", container)), True
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
     return f(self, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
WARNING:kivy:stderr:     return self.get(url, **self._set_request_timeout(kwargs))
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
     return self.request('GET', url, **kwargs)
WARNING:kivy:stderr:     return self.request('GET', url, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
     resp = self.send(prep, **send_kwargs)
WARNING:kivy:stderr:     resp = self.send(prep, **send_kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
     r = adapter.send(request, **kwargs)
WARNING:kivy:stderr:     r = adapter.send(request, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
WARNING:kivy:stderr:     timeout=timeout
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
     timeout_obj = self._get_timeout(timeout)
WARNING:kivy:stderr:     timeout_obj = self._get_timeout(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
     return Timeout.from_float(timeout)
WARNING:kivy:stderr:     return Timeout.from_float(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
     return Timeout(read=timeout, connect=timeout)
WARNING:kivy:stderr:     return Timeout(read=timeout, connect=timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
     self._connect = self._validate_timeout(connect, 'connect')
WARNING:kivy:stderr:     self._connect = self._validate_timeout(connect, 'connect')
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
     "int or float." % (name, value))
WARNING:kivy:stderr:     "int or float." % (name, value))
 ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
WARNING:kivy:stderr: ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
 
WARNING:kivy:stderr: 
DEBUG:__main__:clicked toggle_advanced()
DEBUG:__main__:...exiting toggle_advanced()
[INFO   ] [GL          ] NPOT texture support is available
INFO:kivy:[GL          ] NPOT texture support is available
INFO:__main__:Warning:  This tool is for test and evaulation use only
and is not supported by Puppet.  The images used are NOT
secure and must not be used for production use.
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: Retry(total=0, connect=None, read=False, redirect=None, status=None) -> Retry(total=Retry(total=0, connect=None, read=False, redirect=None, status=None), connect=None, read=None, redirect=0)
WARNING:requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: localhost
 Exception in thread Thread-2:
WARNING:kivy:stderr: Exception in thread Thread-2:
 Traceback (most recent call last):
WARNING:kivy:stderr: Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
     self.run()
WARNING:kivy:stderr:     self.run()
   File "/usr/lib/python2.7/threading.py", line 754, in run
WARNING:kivy:stderr:   File "/usr/lib/python2.7/threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
WARNING:kivy:stderr:     self.__target(*self.__args, **self.__kwargs)
   File "./main.py", line 703, in update_status
WARNING:kivy:stderr:   File "./main.py", line 703, in update_status
     self.daemon_status = self.daemon_alive()
WARNING:kivy:stderr:     self.daemon_status = self.daemon_alive()
   File "./main.py", line 862, in daemon_alive
WARNING:kivy:stderr:   File "./main.py", line 862, in daemon_alive
     version_info = self.cli.version()
WARNING:kivy:stderr:     version_info = self.cli.version()
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/api/daemon.py", line 76, in version
     return self._result(self._get(url), json=True)
WARNING:kivy:stderr:     return self._result(self._get(url), json=True)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
     return f(self, *args, **kwargs)
WARNING:kivy:stderr:     return f(self, *args, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/docker/client.py", line 139, in _get
     return self.get(url, **self._set_request_timeout(kwargs))
WARNING:kivy:stderr:     return self.get(url, **self._set_request_timeout(kwargs))
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 515, in get
     return self.request('GET', url, **kwargs)
WARNING:kivy:stderr:     return self.request('GET', url, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
     resp = self.send(prep, **send_kwargs)
WARNING:kivy:stderr:     resp = self.send(prep, **send_kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
     r = adapter.send(request, **kwargs)
WARNING:kivy:stderr:     r = adapter.send(request, **kwargs)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
     timeout=timeout
WARNING:kivy:stderr:     timeout=timeout
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 582, in urlopen
     timeout_obj = self._get_timeout(timeout)
WARNING:kivy:stderr:     timeout_obj = self._get_timeout(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 309, in _get_timeout
     return Timeout.from_float(timeout)
WARNING:kivy:stderr:     return Timeout.from_float(timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 154, in from_float
     return Timeout(read=timeout, connect=timeout)
WARNING:kivy:stderr:     return Timeout(read=timeout, connect=timeout)
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 97, in __init__
     self._connect = self._validate_timeout(connect, 'connect')
WARNING:kivy:stderr:     self._connect = self._validate_timeout(connect, 'connect')
   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
WARNING:kivy:stderr:   File "/home/geoff/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/timeout.py", line 127, in _validate_timeout
     "int or float." % (name, value))
WARNING:kivy:stderr:     "int or float." % (name, value))
 ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
WARNING:kivy:stderr: ValueError: Timeout value connect was Timeout(connect=60, read=60, total=None), but it must be an int or float.
 
WARNING:kivy:stderr: 
^CERROR:__main__:someone pressed ctrl+c - exit
```

**Comment by GeoffWilliams** [comment]
This is https://github.com/requests/requests/issues/4160

**Comment by GeoffWilliams** [comment]
So bizarre - above error perfectly matches the described fixed bug in requests library and is 100% reproducible using the testcase linked, however the downgrade fix doesn't work and neither does the upgrade to latest 2.18.4!  ... It appears my system is hosed in ways I don't understand.  The _fix_ is to use a virtualenv for pe_kit and then everything instantly starts working with either 2.17x or 2.18.4 version of requests library - wth

Closing this bug and ticketing for virtualenv support for linux since it seems mandatory
